variable "mongo_user" {}
variable "mongo_password" {}
variable "polaris_api_port" {}
variable "telegram_bot_port" {}
variable "telegram_token" {}
variable "ngrok_url" {}
variable "ngrok_port" {}
variable "server_user" {}
variable "docker_username" {}