version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_HOST=mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - polaris_network
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - polaris_network

  polaris_api:
    build: .
    container_name: polaris_api
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    volumes:
      - /home/atorres/Dev/models:/models  # Monta os modelos dentro do container
      - polaris_faiss:/faiss  # Persistência do FAISS
    networks:
      - polaris_network
    environment:
      - FAISS_INDEX_PATH=/faiss/faiss_memory.index
      - MODEL_PATH=/models/Meta-Llama-3-8B-Instruct.Q4_0.gguf
      - MONGO_URI=mongodb://admin:adminpassword@mongodb:27017/

volumes:
  mongodb_data:
    driver: local
  polaris_faiss:
    driver: local

networks:
  polaris_network:
    driver: bridge
