version: '3.8'

services:
  polaris_api:
    build: .
    container_name: polaris_api
    ports:
      - "8000:8000"
    volumes:
      - /home/atorres/Dev/models:/models  # Monta a pasta local dentro do container
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge
