version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - polaris_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - polaris_network

  polaris-api:
    build:
      context: .
      dockerfile: ./polaris-api/Dockerfile
    container_name: polaris-api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017/polaris_db?authSource=admin
    networks:
      - polaris_network
    volumes:
      - ./polaris-api:/app

  telegram-bot:
    build:
      context: .
      dockerfile: ./telegram-bot/Dockerfile
    container_name: telegram-bot
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - polaris-api
    environment:
      - POLARIS_API_URL=http://polaris-api:8000/inference/
      - TELEGRAM_TOKEN=7892223046:AAFyfB9HHMOtZKAeIEnGomc6tkdQFJKsH7s
    networks:
      - polaris_network
    volumes:
      - ./telegram-bot:/app

volumes:
  mongodb_data:
    driver: local

networks:
  polaris_network:
    driver: bridge
